'use strict'


export const GET_ACTIVITIES = 'GET_ACTIVITIES'
export const GET_ACTIVITY = 'GET_ACTIVITY'
export const WATCH_ACTIVITY = 'WATCH_ACTIVITY'
export const CANCEL_WATCH_ACTIVITY = 'CANCEL_WATCH_ACTIVITY'
export const GET_TEAM = 'GET_TEAM'
